version: '3.4'

services:
  oev:
    image: abiosoft/caddy:0.11.0-no-stats
    ports:
    - "2015:2015"
    volumes:
    - "./oev/src:/srv"
    # network_mode: host
  tilecache:
    image: abiosoft/caddy:0.11.0-no-stats
    ports:
    - "2016:2015"
    volumes:
    - "./tilecache/Caddyfile:/etc/Caddyfile"
    - "./tilecache/tmp:/tmp/caddy-cache"
    environment:
    - http_proxy
    - https_proxy
    - no_proxy
  osm-cache:
    image: abiosoft/caddy:0.11.0-no-stats
    ports:
    - "2018:2015"
    volumes:
    - "./osm-cache/Caddyfile:/etc/Caddyfile"
    - "./osm-cache/tmp:/tmp/caddy-cache"
    environment:
    - http_proxy
    - https_proxy
    - no_proxy
  # bigtile:
  #   image: abiosoft/caddy:0.11.0-no-stats
  #   ports:
  #   - "2017:2015"
  #   volumes:
  #   - "/c/Users/a003146/perso/oev-navigation/bigtile/Caddyfile:/etc/Caddyfile"
  #   - "/c/Users/a003146/perso/oev-navigation/bigtile/:/srv"